**Pandas**
1. Pandas is python library which can be use for data analysis.
2. Intially Pandas are called as panel data
3. Pandas is open Source python library which can be use for data manipulation.
4. using pandas we can create data series as well as data frame.
5. Data series represent data in single dimension array format
6. Data frame represent data in two dimension array format

**Advantage :**

1. easy to learn
2. very powerfull for data analysis
3. save time for developer to manual work

**Disadvantage**

1. USe more memory for large data processing
2. not ideal for real time big data analysis.

**Exercise 1. Create Single Dimension array without data**

In [3]:
from operator import concat

import pandas as pd
from pandas.conftest import index

s = pd.Series()
print(s)

Series([], dtype: object)

**Exercise 2. Create Single Dimension Array with data**

In [29]:
import pandas as pd
Data = [10,20,30,40,50,60,70,80,90,100]
s = pd.Series(Data,index=[1,2,3,4,5,6,7,8,9,10])

In [30]:
s

1      10
2      20
3      30
4      40
5      50
6      60
7      70
8      80
9      90
10    100
dtype: int64

**Exercise 3. create series by using Data Dictionary**

In [34]:
import pandas as pd

data = {"a": 10, "b": 20, "c": 30}
s = pd.Series(data)

In [32]:
s

a    10
b    20
c    30
dtype: int64

**Exercise 4. create series by using Data Dictionary and own indexes**

In [35]:
import pandas as pd

data = {"a": 10, "b": 20, "c": 30}
s = pd.Series(data,index=["a","b","d","c"])

In [36]:
s

a    10.0
b    20.0
d     NaN
c    30.0
dtype: float64

In [38]:
s["a"]

np.float64(10.0)

**Exercise 5. Create series for only one value based on number of indexes**

In [39]:
import pandas as pd
data = pd.Series(10,index=[1,2,3,4,5,6,7])

In [40]:
data

1    10
2    10
3    10
4    10
5    10
6    10
7    10
dtype: int64

**Exercise 6. Create Empty Data Frame**

In [21]:
import pandas as pd
data = pd.DataFrame()
print(data)

Empty DataFrame
Columns: []
Index: []

**Exercise 7. Create Data Frame with Data(using Nested List)**

In [25]:
import pandas as pd

data = [
    [1, "Afzal",32,"Allahabad"],
    [2,"Arshad",30,"Basti"],
    [3,"Amjad",27,"New Delhi"],
    [4,"Asjad",23,"Chandigarh"]
]

col = ["Sno", "Name", "Age" , "Address"]

df = pd.DataFrame(data, columns = col)

   Sno    Name  Age     Address
0    1   Afzal   32   Allahabad
1    2  Arshad   30       Basti
2    3   Amjad   27   New Delhi
3    4   Asjad   23  Chandigarh

In [28]:
df

   Sno    Name  Age     Address
0    1   Afzal   32   Allahabad
1    2  Arshad   30       Basti
2    3   Amjad   27   New Delhi
3    4   Asjad   23  Chandigarh

**Exercise 8. pull top two data from data Frame**

In [26]:
df.head(2)

   Sno    Name  Age    Address
0    1   Afzal   32  Allahabad
1    2  Arshad   30      Basti

**Exercise 9. Pull last two records from Data Frame**

In [41]:
df.tail(2)

   Sno   Name  Age     Address
2    3  Amjad   27   New Delhi
3    4  Asjad   23  Chandigarh

**Exercise 10. we can display data frame column info**

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Sno      4 non-null      int64
 1   Name     4 non-null      object
 2   Age      4 non-null      int64
 3   Address  4 non-null      object
dtypes: int64(2), object(2)
memory usage: 256.0+ bytes

**Exercise 11. Create data frame by using dictionary format**

In [47]:
data = { "Sno":[1,2,3,4],"Name":["Afzal","Arshad","Amjad","Asjad"],
         "Age":[32,30,27,23],"Address":["Allahabad","Basti","New Delhi","Chandigarh"]}

df = pd.DataFrame(data)

df

   Sno    Name  Age     Address
0    1   Afzal   32   Allahabad
1    2  Arshad   30       Basti
2    3   Amjad   27   New Delhi
3    4   Asjad   23  Chandigarh

**Exercise 12. Combine data from multiple data frame**

In [61]:
data1 = {"Sno":[1,2],"Name":["Afzal","Arshad"],
         "Age":[32,30] , "Address":["Allahabad","Basti"]}
df1 = pd.DataFrame(data1)
df1

   Sno    Name  Age    Address
0    1   Afzal   32  Allahabad
1    2  Arshad   30      Basti

In [79]:
data2 = [
    [3,"Amjad",27,"New Delhi"],
    [4,"Asjad",23,"Chandigarh"],
]
df2 = pd.DataFrame(data2,columns=["Sno","Name","Age","Address"])
df2

   Sno   Name  Age     Address
0    3  Amjad   27   New Delhi
1    4  Asjad   23  Chandigarh

In [77]:
df3= pd.concat([df1,df2])
df3

   Sno    Name  Age     Address
0    1   Afzal   32   Allahabad
1    2  Arshad   30       Basti
0    3   Amjad   27   New Delhi
1    4   Asjad   23  Chandigarh

**Exercise 13. Create Data Frame from csv format and recreate file in html format**

In [69]:
emp = pd.read_csv("emp.csv")
emp.to_html("emp.html")
print("Html file Created")

Html file Created

**Exercise 14. Update 2000 Salary for every employee and recreate emp file**

In [70]:
df = pd.read_csv("emp.csv")
df['SAL'] = df['SAL'] + 2000

In [80]:
df.to_csv("emp.csv",index=False)

**Exercise 15. Create data from emp.csv file and also create Pie chart**

In [81]:
emp = pd.read_csv("emp.csv")
emp

,EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,UPDATED_DATE
0,7369,SMITH,CLERK,7902.0,17-12-1980,2800,NaN,20,1/1/2022
1,7499,ALLEN,SALESMAN,7698.0,20-02-1981,3600,300.0,30,1/1/2022
2,7521,WARD,SALESMAN,7698.0,22-02-1981,3250,500.0,30,1/1/2022
3,7566,JONES,MANAGER,7839.0,4/2/1981,4975,NaN,20,1/5/2022
4,7654,MARTIN,SALESMAN,7698.0,21-09-1981,3250,1400.0,30,1/3/2022
5,7698,SGR,MANAGER,7839.0,5/1/1981,4850,NaN,30,1/4/2022
6,7782,RAVI,MANAGER,7839.0,6/9/1981,4450,NaN,10,1/2/2022
7,7788,SCOTT,ANALYST,7566.0,19-04-1987,5000,NaN,20,1/2/2022
8,7839,KING,PRESIDENT,NaN,1/11/1981,7000,NaN,10,1/2/2022
9,7844,TURNER,SALESMAN,7698.0,9/8/1981,3500,0.0,30,1/2/2022
10,7876,ADAMS,CLERK,7788.0,23-05-1987,3100,NaN,20,1/3/2022
11,7900,JAMES,CLERK,7698.0,12/3/1981,2950,NaN,30,1/3/2022
12,7902,FORD,ANALYST,7566.0,12/3/1981,5000,NaN,20,1/3/2022
13,7934,MILLER,CLERK,7782.0,1/3/1982,3300,NaN,10,1/3/2022
14,1234,SEKHAR,doctor,7777.0,NaN,2667,78.0,80,1/3/2022
15,7369,SMITH,CLERK,7902.0,17-12-1980,2800,NaN,20,1/4/2022
16,7499,ALLEN,SALESMAN,7698.0,20-02-1981,3600,300.0,30,1/4/2022
17,7521,WARD,SALESMAN,7698.0,22-02-1981,3250,500.0,30,1/4/2022
18,7566,JONES,MANAGER,7839.0,4/2/1981,4975,NaN,20,1/4/2022
19,7654,MARTIN,SALESMAN,7698.0,21-09-1981,3250,1400.0,30,1/5/2022
20,7698,SGR,MANAGER,7839.0,5/1/1981,4850,NaN,30,1/5/2022
21,7782,RAVI,MANAGER,7839.0,6/9/1981,4450,NaN,10,1/5/2022
22,7788,SCOTT,ANALYST,7566.0,19-04-1987,5000,NaN,20,1/6/2022
23,7839,KING,PRESIDENT,NaN,1/11/1981,7000,NaN,10,1/6/2022
24,7844,TURNER,SALESMAN,7698.0,9/8/1981,3500,0.0,30,1/6/2022
25,7876,ADAMS,CLERK,7788.0,23-05-1987,3100,NaN,20,1/6/2022
26,7900,JAMES,CLERK,7698.0,12/3/1981,2950,NaN,30,1/7/2022
27,7902,FORD,ANALYST,7566.0,12/3/1981,5000,NaN,20,1/7/2022
28,7934,MILLER,CLERK,7782.0,1/3/1982,3300,NaN,10,1/7/2022
29,1234,RAM,CLERK,7457.0,NaN,2494,588.0,80,1/7/2022

**Exercise 16. Create csv file where employee salary greater than 3000 from data frame**

In [85]:
new_emp = emp[emp['SAL'] > 3000]
new_emp.to_csv("New_emp_3000.csv")

**Exercise 17. pull data from Df with selected column**

In [91]:
new_emp[["EMPNO","ENAME",'JOB','SAL','DEPTNO']]

    EMPNO   ENAME        JOB   SAL  DEPTNO
1    7499   ALLEN   SALESMAN  3600      30
2    7521    WARD   SALESMAN  3250      30
3    7566   JONES    MANAGER  4975      20
4    7654  MARTIN   SALESMAN  3250      30
5    7698     SGR    MANAGER  4850      30
6    7782    RAVI    MANAGER  4450      10
7    7788   SCOTT    ANALYST  5000      20
8    7839    KING  PRESIDENT  7000      10
9    7844  TURNER   SALESMAN  3500      30
10   7876   ADAMS      CLERK  3100      20
12   7902    FORD    ANALYST  5000      20
13   7934  MILLER      CLERK  3300      10
16   7499   ALLEN   SALESMAN  3600      30
17   7521    WARD   SALESMAN  3250      30
18   7566   JONES    MANAGER  4975      20
19   7654  MARTIN   SALESMAN  3250      30
20   7698     SGR    MANAGER  4850      30
21   7782    RAVI    MANAGER  4450      10
22   7788   SCOTT    ANALYST  5000      20
23   7839    KING  PRESIDENT  7000      10
24   7844  TURNER   SALESMAN  3500      30
25   7876   ADAMS      CLERK  3100      20
27   7902    FORD    ANALYST  5000      20
28   7934  MILLER      CLERK  3300      10

**Delete Data from your Data frame and store data in csv file**

In [98]:
del_10_deptno = new_emp[new_emp['DEPTNO'] !=10]
del_10_deptno.to_csv("emp_20_30.csv")

In [99]:
del_10_deptno

,EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,UPDATED_DATE
1,7499,ALLEN,SALESMAN,7698.0,20-02-1981,3600,300.0,30,1/1/2022
2,7521,WARD,SALESMAN,7698.0,22-02-1981,3250,500.0,30,1/1/2022
3,7566,JONES,MANAGER,7839.0,4/2/1981,4975,NaN,20,1/5/2022
4,7654,MARTIN,SALESMAN,7698.0,21-09-1981,3250,1400.0,30,1/3/2022
5,7698,SGR,MANAGER,7839.0,5/1/1981,4850,NaN,30,1/4/2022
7,7788,SCOTT,ANALYST,7566.0,19-04-1987,5000,NaN,20,1/2/2022
9,7844,TURNER,SALESMAN,7698.0,9/8/1981,3500,0.0,30,1/2/2022
10,7876,ADAMS,CLERK,7788.0,23-05-1987,3100,NaN,20,1/3/2022
12,7902,FORD,ANALYST,7566.0,12/3/1981,5000,NaN,20,1/3/2022
16,7499,ALLEN,SALESMAN,7698.0,20-02-1981,3600,300.0,30,1/4/2022
17,7521,WARD,SALESMAN,7698.0,22-02-1981,3250,500.0,30,1/4/2022
18,7566,JONES,MANAGER,7839.0,4/2/1981,4975,NaN,20,1/4/2022
19,7654,MARTIN,SALESMAN,7698.0,21-09-1981,3250,1400.0,30,1/5/2022
20,7698,SGR,MANAGER,7839.0,5/1/1981,4850,NaN,30,1/5/2022
22,7788,SCOTT,ANALYST,7566.0,19-04-1987,5000,NaN,20,1/6/2022
24,7844,TURNER,SALESMAN,7698.0,9/8/1981,3500,0.0,30,1/6/2022
25,7876,ADAMS,CLERK,7788.0,23-05-1987,3100,NaN,20,1/6/2022
27,7902,FORD,ANALYST,7566.0,12/3/1981,5000,NaN,20,1/7/2022